name: itk-3dvis
channels:
  - conda-forge
  - defaults
dependencies:
  - antlr-python-runtime=4.7.2
  - asn1crypto=0.24.0
  - atk=2.25.90
  - attrs=19.1.0
  - backcall=0.1.0
  - bleach=3.1.0
  - bokeh=1.1.0
  - boto3=1.9.135
  - botocore=1.12.136
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cairo=1.16.0
  - cartopy=0.17.0
  - certifi=2019.3.9
  - cf-units=2.1.1
  - cffi=1.12.3
  - cftime=1.0.3.4
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=0.8.1
  - cryptography=2.5
  - curl=7.64.0
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=1.2.0
  - dask-core=1.2.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - distributed=1.27.0
  - docutils=0.14
  - entrypoints=0.3
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gdk-pixbuf=2.36.12
  - geos=3.7.1
  - gettext=0.19.8.1
  - glib=2.58.3
  - gobject-introspection=1.58.2
  - graphite2=1.3.13
  - gstreamer=1.14.4
  - gtk2=2.24.31
  - harfbuzz=2.4.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.0
  - icu=58.2
  - idna=2.8
  - ipydatawidgets=4.0.0
  - ipykernel=5.1.0
  - ipympl=0.2.1
  - ipyscales=0.3.0
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - iris=2.2.0
  - itk=4.13.2
  - itkwidgets=0.16.1
  - jedi=0.13.3
  - jinja2=2.10.1
  - jmespath=0.9.4
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.32
  - locket=0.2.0
  - lxml=4.3.3
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - mistune=0.8.4
  - msgpack-python=0.6.1
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - netcdf4=1.5.0.1
  - notebook=5.7.8
  - numpy=1.16.3
  - olefile=0.46
  - openblas=0.3.5
  - openssl=1.0.2r
  - owslib=0.17.1
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.7.2
  - pandocfilters=1.4.2
  - pango=1.40.14
  - parso
  - partd=0.3.9
  - pcre=8.41
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.1
  - pixman=0.34.0
  - proj4=5.2.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - psutil=5.6.2
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pyepsg=0.4.0
  - pygments=2.3.1
  - pykdtree=1.3.1
  - pyke=1.1.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyproj=1.9.6
  - pyqt=5.6.0
  - pyrsistent=0.15.1
  - pyshp=2.1.0
  - pysocks=1.6.8
  - python=3.7.1
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyyaml=5.1
  - pyzmq=18.0.1
  - qt=5.6.2
  - readline=7.0
  - requests=2.21.0
  - s3transfer=0.2.0
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=41.0.1
  - shapely=1.6.4
  - sip=4.18.1
  - six=1.12.0
  - sortedcontainers=2.1.0
  - sqlite=3.26.0
  - tblib=1.3.2
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=6.0.2
  - traitlets=4.3.2
  - traittypes=0.2.1
  - udunits2=2.2.27.6
  - urllib3=1.24.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zict=0.1.4
  - zlib=1.2.11
  - zstandard=0.11.0
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=8.2.0
